<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BLOG</title>
</head>
<body>
	<label align="center"><h1>CATEGORY PAGE</h1></label>
	<table border="1" align="center">
		<tr align="center">
			<td><?php if ($_SESSION['role'] == 'admin'):?>
			<div class="dis-btn-ele"><button> <a href="Category.php?page=add" style="color: black; text-decoration: none;">ADD CATEGORY</a></button> </div></td>
		<?php endif; ?> 
			<td><div class="dis-btn-ele"><button><a href="blog.php?page=grid" style="color: black; text-decoration: none;">SHOW POST</a> </button></div></td>
			<td><div class="dis-btn-ele"><button> <a href="Sub_category.php?page=grid" style="color: black; text-decoration: none;">SHOW SUB CATEGORY</a></button> </div></td>
			<td><div class="dis-btn-ele"><button><a href="login.php?page=logout" style="color: black; text-decoration: none;">LOGOUT</a></button> </div></td>

	</table>

	<table>
		<tr style="background: lightgoldenrodyellow;">
			<th>CATEGORY ID</th>
			<th>NAME</th>
			<th>STATUS</th>
			<th>TOTAL POST</th>
		</tr>
		<?php foreach ($categorys as $category): ?>
		<tr style="background:whitesmoke;">
			<td align="center"><?php echo $category['category_id'] ?></td>
			<td align="center"><?php echo $category['name'] ?></td>
			<td align="center"><?php echo $category['status'] ?></td>
			<?php 
			if ($_SESSION['role'] == 'admin') {
				$sql = "SELECT * FROM `post` WHERE `category` = '{$category['category_id']}'";	
			}
			else{
				
			$sql = "SELECT * FROM `post` WHERE `category` = '{$category['category_id']}' && `user_id` = '{$_SESSION['id']}'";
			}
			$row = $adapter->numRow($sql);  
			?>
			<td align="center"><?php echo $row ?></td>
		</tr>
	<?php endforeach; ?>
	</table>
</body>
</html>