<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BLOG</title>
</head>
<body>

	<form method="POST" action="login.php?page=auth" >
		<center><label><h1>Log In</h1></label></center>
		<table border="1" align="center" style="background:whitesmoke; width: 450px; height:200px;">
			<tr align="center">
				<td>Email:</td>
				<td><input type="text" name="email"></td>
			</tr>
			<tr align="center">
				<td>Password:</td>
				<td><input type="password" name="password"></td>
			</tr>
			<tr align="center">
				<td colspan="2"><button type="submit" name="submit" value="submit">Submit</button></td>
			</tr>
		</table>
	</form>

</body>
</html>