<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BLOG</title>
</head>
<body>
<label align="center"><h1>ADD SUB CATEGORY</h1></label>
<form method="POST" action="Sub_category.php?page=insert">
	<table align="center" style="background:whitesmoke;">
		<tr align="center">
			<td>CATEGORY</td>
			<td><input type="text" name="sub_category"></td>
		</tr>
		<tr align="center">
			<td>Status</td>
			<td>
					<select name="status">
					<option value="1">ACTIVE</option>
					<option value="2">INACTIVE</option>
					</select>
			</td>
		</tr>
		<tr align="center">
			<td>Category</td>
			<td>
				<select name="category">
				<?php foreach ($categorys as $category):?>
				<option value="<?php echo $category['category_id'] ?>"><?php echo $category['name'] ?></option>
				<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr align="center">
			<td colspan="2"><button type="submit" name="submit" value="submit">Submit</button></td>
		</tr>
	</table>
</form>

</body>
</html>